Molecules/Taskの作成
xitras7776/saiho-frontend-basic-2022-todoapp pull request #6
Opened 2022-11-16 10:00 UTC by xitras7776

2022-12-22 03:08 UTC, xitras7776 reviewed
いくつかわからない点がありますが一旦レビューお願いします

2022-12-22 03:08 UTC, xitras7776 commented on src/components/Molecules/Task/story.jsx
> +};
onEditComplete is not a function の表示が出てしまい上手く表示されません

onTaskcompleteに関しては全く反応してくれません

2022-12-22 03:08 UTC, xitras7776 commented on src/components/Molecules/Task/index.jsx
> +        </StyledTaskArea>
三項演算子で inputの表示分岐はできましたが、inputを表示した後にonEditCompleteが効いていない？っぽくてinputを表示させなくする操作ができません…

2022-12-24 02:49 UTC, Hasegawa62 commented on src/components/Molecules/Task/index.jsx
> +          onTaskChange={(taskName) => {
atoms/Inputのindex.tsxを見ると、StyledInput要素に渡せるpropsはonEditCompleteではないでしょうか？
![image](https://user-images.githubusercontent.com/94204610/209418484-2c7872f5-93e9-4577-8226-e2047b25d251.png)
ここが原因で動いていないのかなと思います、試してみてください！

2022-12-25 14:31 UTC, higashiji2000 requested changes
基本的な動作は問題なさそうです！
三項演算子とかも使えていてGoodです。

2022-12-25 14:31 UTC, higashiji2000 commented on src/components/Molecules/Task/story.jsx
> +  onTaskcomplete:() => console.log("task completed"),
```suggestion
  onTaskComplete:() => console.log("task completed"),
```
ここ修正すればlogがちゃんと出そうです。

2022-12-25 14:31 UTC, higashiji2000 commented on src/components/Molecules/Task/story.jsx
> +  onEditComplete: () => console.log("taskname changed ${taskName}"),
```suggestion
  onEditComplete: (taskName) => console.log(`taskname changed ${taskName}`),
```
文字列内部で変数を参照したいときは バッククオート `のテンプレートリテラルでいきましょう！
また、変更後のタスク名を表示するためには引数として受け取れるようにしておくのも必要ですね。、

2022-12-25 14:31 UTC, higashiji2000 commented on src/components/Molecules/Task/index.jsx
> +`;
<img width="844" alt="image" src="https://user-images.githubusercontent.com/83479175/209471815-3868ea90-ed21-441a-b8c3-e16c9557487c.png">
ここに記述追加して、EditButtonが端に寄るようにしましょう

2022-12-25 14:31 UTC, higashiji2000 commented on src/components/Molecules/Task/index.jsx
> +import StyledInput from "../../../components/Atoms/Input";
```suggestion
import EditButton from "../../../components/Atoms/EditButton";
import Checkbox from "../../../components/Atoms/Checkbox";
import Input from "../../../components/Atoms/Input";
```
基本コンポーネント名はそのまま呼んでおいた方がいいです！
あとから、「このコンポーネントはどこで使われているんだっけ」と思った時に名前を変えてインポートしていると検索しづらいです。

2022-12-25 14:52 UTC, higashiji2000 approved these changes
LGTM 🆗

2022-12-25 14:53 UTC, merged